filebeat.inputs:
  - type: filestream
    id: dns-logs-stream
    enabled: true
    paths:
      - /usr/share/filebeat/*.log
    fields:
      log_type: dns_access 
    fields_under_root: true  
    scan_frequency: 5s
    parsers:
      - multiline:
          pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}:'
          negate: true
          match: after

    
output.logstash:
  hosts: ["elk:5044"]
  ssl.enabled: false
  timeout: 15s
